language: php

sudo: required

install: composer install

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

script: phpunit -c test/phpunit.xml test

notifications:
    on_success: never
    on_failure: always
